run:
  skip-dirs:
    - api/client
  modules-download-mode: readonly
issues:
  exclude-use-default: false
linters:
  enable:
    - gofmt
    - goimports
    - golint
    - govet
linters-settings:
  goimports:
    local-prefixes: github.com/spinnaker/kleat
