builds:
- ldflags:
    - -s -w -X github.com/spinnaker/kleat/cmd.version={{.Version}} -X github.com/spinnaker/kleat/cmd.commit={{.Commit}} -X github.com/spinnaker/kleat/cmd.date={{.Date}}
  # By default, will build each specified $GOOS for the default $GOARCH options of 386 and amd64.
  # If necessary in the future, can specify non-default $GOARCH options under `goarch` key per
  # https://goreleaser.com/customization/build/.
  goos:
    - darwin
    - linux
    - windows
