name: default
version: master-latest-unvalidated
providers:
  kubernetes:
    enabled: true
    accounts:
    - name: k8s
      providerVersion: 2
      context: spinnaker
      configureImagePullSecrets: true
      cacheThreads: 1
      omitNamespaces:
      - default
      - kube-public
      - kube-system
      - docs-site-v1
      kubeconfigFile: /var/secrets/k8s-kubeconfig
      checkPermissionsOnStartup: true
    primaryAccount: k8s
  appengine:
    enabled: true
    accounts:
      - name: my-appengine-account
        project: spinnaker-maggie
        jsonPath: var/secrets/appengine-account.json
        sshTrustUnknownHosts: true
    primaryAccount: my-appengine-account
  google:
    enabled: true
    accounts:
      - name: my-gce-account
        project: spinnaker-maggie
        jsonPath: /var/secrets/gce-account.json
        alphaListed: true
        consul:
          enabled: true
          agentEndpoint: localhost
          agentPort: 8500
          datacenters: []
        regions:
          - us-east1-b
    primaryAccount: my-gce-account
    bakeryDefaults:
      templateFile: gce.json
      baseImages:
        - baseImage:
            id: my-image-id
            shortDescription: my short description
            detailedDescription: my detailed description
            imageFamily: true
          virtualizationSettings:
            sourceImage: my-source-image
            sourceImageFamily: my-source-image-family
      zone: us-central1-f
      network: default
      networkProjectId: my-network-project-id
      useInternalIp: true
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    project: ezimanyi-spinnaker-dev
    bucket: ezimanyi-spinnaker-dev-pipelines
    rootFolder: front50
    bucketLocation: us
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}